
### GET request to example server


POST localhost:8080/person/addPerson
Content-Type: application/json

{
  "name": "Juan",
  "lastName": "Gómez",
  "email": "juangomez@gmail.com"
}

###

POST localhost:8080/person/update
Content-Type: application/json

{
  "idPerson": 1,
  "name": "Juan",
  "lastName": "Gómes",
  "email": "juanchogomez@hotmail.com",
  "address": "Cra 87#34 H"
}

###

DELETE localhost:8080/person/delete/1
Content-Type: application/json

###

POST localhost:8080/companys/add
Content-Type: application/json

{
 "name": "Contoso",
 "cityOfOperation": "Bogotá, D.C",
 "address": "Calle 182 #45H"
}

###

POST localhost:8080/departaments/add
Content-Type: application/json

{
  "description": "Marketing",
  "company": {
    "idCompany": 1
  }
}

###

DELETE localhost:8080/departaments/1
Content-Type: application/json

###


POST localhost:8080/users/add
Content-Type: application/json

{
  "name": "Pedro",
  "lastName": "Pelaez",
  "phoneNumber": "311 9812 121",
  "salary":30000,
  "address": "Calle76",
  "userStatus": "Active",
  "position": "Gerente",
  "cityOfResidence": "Bogotá, D.C",
  "departament": {
    "idDepartament": 102
  }
}