
### GET request to example server


POST localhost:8080/person/addPerson
Content-Type: application/json

{
  "name": "Juan",
  "lastName": "Gómez",
  "email": "juangomez@gmail.com"
}

###

POST localhost:8080/person/update
Content-Type: application/json

{
  "idPerson": 1,
  "name": "Juan",
  "lastName": "Gómes",
  "email": "juanchogomez@hotmail.com",
  "address": "Cra 87#34 H"
}

###

DELETE localhost:8080/person/delete/1
Content-Type: application/json

###